### ISSUE TITLE
Miles to meters conversions

### ISSUE THREAD

**Issue by kwg** [cameron-henkel/GoGeoHeatmap#1]
2 miles: 3219m
4 miles: 6437m 

The test circles may be useful in creating a mask for the 2 mile radii after setting the desired radius to 4 miles. If that doesn't work out we could try making 2 heatmaps.

We should work off of the assumption that all rides originated from the closest stop to the destination. So masking off the areas that are within 2 miles of a stop should leave us with the possible destination areas. Once we have that we can look at how the heatmap is handling the overlaps. This may be something that I need to toss into photoshop and color by hand.

**Comment by cameron-henkel** [comment]
Masks are supported now, although our specific implementation still requires some photoshopping. Next major update will hopefully resolve this.
